---
version: "3.8"

services:
  playground:
    image: "yingzhuo/playground:latest"
    container_name: "playground"
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    command:
      - "--other-param-here"
