# ----------------------------------------------------------------------------------------------------------------------
# SSL配置
#  (自签名)
# ----------------------------------------------------------------------------------------------------------------------
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: "pkcs12"
    key-store: "classpath:ssl/server.keystore.p12"
    key-alias: "server"
    key-store-password: "123456"
    key-password: "123456"
    client-auth: none
