# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  config:
    import:
      - "optional:classpath:/config/config.yml"
      - "optional:classpath:/config/config-dev.yml"
